### ISSUE TITLE
Página de Inicio - Gestión del Empleado

### ISSUE THREAD

**Issue by Sao912** [ISWPOLI/CASA#2]
**Página de Inicio y Gestión del Empleado.**

- [x] Diseño de interfaz de acuerdo a mockups @nihilarion 
- [x] Implementación de filtro por empleado @nihilarion 
- [x] Implementación de ventana con información del empleado @nihilarion 
- [x] Implementación de agregar empleado @nihilarion

**Comment by nihilarion** [comment]
se agrego carpeta con el css para implementar en el modelo de nomina

**Comment by nihilarion** [comment]
se implemento la ventana de inicio/buscar empleado en el codigo fuente

**Comment by nihilarion** [comment]
se agrego template que muestra la información del empleado que previamente se seleccione en la ventana buscar_empleado.html

**Comment by nihilarion** [comment]
se implemento el template para agregar nuevo empelado
