### ISSUE TITLE
Modelo de Nómina - Gestion del Empleado 

### ISSUE THREAD

**Issue by Sao912** [ISWPOLI/CASA#3]
**Página de Información del Colaborador.**

- [x] Diseño de interfaz de acuerdo a mockups @hrodriguezg 
- [x] Implementación de Menú de desglose @hrodriguezg 
- [x] Mostrar información del empleado @hrodriguezg 
- [x] Implementación Agregar Hoja de Vida @hrodriguezg 
- [x] Implementación de gestión y enviar memorando @hrodriguezg 
- [x] Implementación de reportes básicos del empleado @hrodriguezg

**Comment by hrodriguezg** [comment]
**Diseño de interfaz de acuerdo a mockups**
Se crea el diseño de interfaz (maquetacion) donde ira la información del Empleado se aloja en la carpeta de Modelo de Nomina/inf-empleado, donde también contiene subcarpetas necesarias para el desarrollo de esta pagina donde van los CSS e imagenes y los JavaScript

**Comment by hrodriguezg** [comment]
Se realiza menú (Sidebar Izquierdo) desplegable verticalmente, con las posibles opciones de los formularios y/o funciones que trabajará este modulo. Se corrige algunos puntos en cuanto al menú que se presento en el mockups  y se deja mas a la realidad de lo que podía ser un software de nomina

**Comment by hrodriguezg** [comment]
Se Creo pagina mostrando la informacion de los Empleados que están en el sistema con sus opciones
posibles de Editar o Eliminar.

**Comment by hrodriguezg** [comment]
Se implemento en la pagina donde se visualiza la información del Empleado el botón de Ingresar Hoja de Vida y su respectivo formulario para llenar y guardar.

**Comment by hrodriguezg** [comment]
Se Creo pagina con muestra del listado de los memorandos y sus respectivas acciones (botones) de Edición y eliminación.  Ahí mismo se creo el formulario para crear un memorando y la posibiliadad de enviarlo al usuarios vía correo.

**Comment by hrodriguezg** [comment]
Se crea pagina para la gestión de Consultas, donde se podrá realizar consultas por departamento, profesión, salarios o fecha de Ingreso.  Se hicieron correcciones en demás paginas creadas.
