### ISSUE TITLE
Pagina Login

### ISSUE THREAD

**Issue by hrodriguezg** [ISWPOLI/CASA#5]
**Titulo Pagina de Login**
Autenticación del usuario al sistema.
**Tareas asociadas**

- [x] Crear archivo html con los componentes necesarios @sebasc91

- [x] Crear ccs de acuerdo @sebasc91

- [x] Script de validación y muestre mensaje de error @sebasc91

- [x] Implementación de registro de nuevos usuarios @sebasc91

- [x] Implementación de olvido de contraseña @sebasc91

**Comment by sebasc91** [comment]
Se crea el archivo css

https://github.com/ISWPOLI/CASA/tree/master/login/css

**Comment by sebasc91** [comment]
se realiza entrega del script para validación de dato ingresados.

https://github.com/ISWPOLI/CASA/tree/master/login/js

**Comment by sebasc91** [comment]
se carga archivo login.html
https://github.com/ISWPOLI/CASA/tree/master/login/template

**Comment by sebasc91** [comment]
se carga archivo registar.html
https://github.com/ISWPOLI/CASA/tree/master/login/template

**Comment by sebasc91** [comment]
se carga archivo recuperar.html
https://github.com/ISWPOLI/CASA/blob/master/login/template/recuperar.html

**Comment by sebasc91** [comment]
Se revisa los templates creados con el grupo de trabajo. Se da cierre
