### ISSUE TITLE
Modelo de Nómina - Estructura de Nómina

### ISSUE THREAD

**Issue by sebasc91** [ISWPOLI/CASA#6]
**Página de información de la Estructura**

- [x] Diseño de interfaz de acuerdo a mockups en html @nihilarion 
- [x] Mostrar la estructura de nómina - Organigrama @nihilarion 
- [x] Implementación de modificación de la estructura @nihilarion 
- [x] Implementación de información roles politécnico @nihilarion 
- [x] Implementación que permite agregar, modificar y eliminar roles @nihilarion

**Comment by nihilarion** [comment]
se agrega template de estructura organizacional
