### ISSUE TITLE
Modelo de Nómina - Asignación de Tareas

### ISSUE THREAD

**Issue by sebasc91** [ISWPOLI/CASA#7]
**Asignación de Tarea a los Colaboradores**

- [x] Implementación de agregar tareas @hrodriguezg 
- [x] Implementación de asociar colaboradores con tarea nuevas @hrodriguezg 
- [x] Implementación ver tareas pendientes @hrodriguezg 
- [x] Se agrega en el módulo de consultas del Sprint pasado el calendario cuando se escoge la opción de filtrar por fecha de ingreso @hrodriguezg

**Comment by hrodriguezg** [comment]
Se agrega en el menú el módulo Tareas, donde se visualiza dos submenús: Gestión de Tareas y Tareas pendientes. En la página de Gestión de Tareas se muestra el listado de las tareas, sus acciones de posible borrado o edición y un botón donde nos abre el formulario para crear una tarea (el formulario tiene validación de campos). @hrodriguezg

**Comment by hrodriguezg** [comment]
En el formulario para crear Nueva Tarea esta la opción de escoger al responsable que va a realizar la tarea de una lista desplegable de los colaborados, es decir al crear la tarea se debe escoger de una vez a quien se le asignará la tarea. Esto a su vez en la versión de producción deberá ser reflejado en la lista de tareas de la página Gestión de Tareas. @hrodriguezg

**Comment by hrodriguezg** [comment]
Se crea la página para hacer las consultas de las tareas pendientes, donde se muestra solo el listado de las tareas pendientes y el posible filtro por fechas, proyecto o Responsable @hrodriguezg

**Comment by hrodriguezg** [comment]
Se colocar por medio de JavaScript en el input de escoger la fecha el calendario para que sea más practico escoger la fecha a la hora de hacer el filtro por fecha de Ingreso.  esto es una mejora del modulo de consultas del sprint pasado. @hrodriguezg
